defaults: &defaults
  smtp_address: 'smtp.example.com'
  smtp_port: '587'
  smtp_user_name: 'example@mail.com'
  smtp_password: 'my-smtp-password'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

